[project]
name = "lux-roast-bot"
version = "0.1.0"
description = "A simple Discord bot for roasting Lux coin"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.12",
    "anthropic>=0.45.2",
    "discord-py>=2.4.0",
    "emoji>=2.14.1",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "openai>=1.61.1",
    "pillow>=11.1.0",
    "plotly>=6.0.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "selenium>=4.28.1",
    "twilio>=9.4.4",
    "webdriver-manager>=4.0.2",
]
